### ISSUE TITLE
Include BarterDEX as Atomic Swap Implementation

### ISSUE THREAD

**Issue by polycryptoblog** [treygriffith/swap-compatibility#1] opened 2018-01-11 17:56 UTC
BTC, BTCH, Dash,DOGE,Groestlcoin, Litecoin, Syscoin,Viacoin,Vertcoin and Zcash   all have fully working on chain atomic swaps available in Komodo Platform's BarterDEX application.

All of them are compatible with each other as well.  

The chart should be updated to reflect this.

**Comment by treygriffith** [comment] 2018-01-11 17:57
@polycryptoblog can you link me to the GitHub repo with the working atomic swap implementation? Would love to get this updated.

**Comment by polycryptoblog** [comment] 2018-01-11 17:59
Sure https://github.com/KomodoPlatform/BarterDEX,  try it out.  I am not the most technical of people and I was able to get swaps going.  This is a game changer

**Comment by treygriffith** [comment] 2018-01-11 18:57
@polycryptoblog it looks like the actual swap code is here: https://github.com/KomodoPlatform/KomodoPlatform/blob/master/basilisk/basilisk_swap.c

This is a different style of swap than I'm familiar with, so integrating it into the chart will take some time.

For example, it only requires one of the two coins in the swap to support CLTV.

**Comment by treygriffith** [comment] 2018-01-11 19:40
@polycryptoblog I opened issue https://github.com/jl777/SuperNET/issues/553 with the Komodo devs to get an answer to a question before I include it as an atomic swap.

**Comment by polycryptoblog** [comment] 2018-01-11 19:46
The lead developer, jl777  can better help explaining it than me  here is his github,  https://github.com/jl777

**Comment by treygriffith** [comment] 2018-01-16 16:00
Based on my understanding of the protocol in use by BarterDEX (and confirmed by the lead dev), it is not a trustless atomic swap. Closing this issue as I don't consider it appropriate to include a non-trustless atomic swap in the chart.

**Closed as completed by treygriffith** 2018-01-16 16:00 UTC
